"""add new models in db

Revision ID: 13b0f04fb4ff
Revises: 17ac71d091b9
Create Date: 2025-01-14 22:29:39.628174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b0f04fb4ff'
down_revision: Union[str, None] = '17ac71d091b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_cat', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='categorytype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_cat')
    )
    op.create_table('finances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('u_cat_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type_of_operation', sa.Enum('income', 'expense', name='categorytype'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['u_cat_id'], ['user_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finances')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
