"""Rename u_cat_id to category_id

Revision ID: 7dccdf45c155
Revises: e9ba9a2a2a13
Create Date: 2025-01-25 12:19:55.491034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dccdf45c155'
down_revision: Union[str, None] = 'e9ba9a2a2a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finances', sa.Column('category_id', sa.UUID(), nullable=False))
    op.drop_constraint('finances_u_cat_id_fkey', 'finances', type_='foreignkey')
    op.create_foreign_key(None, 'finances', 'user_categories', ['category_id'], ['id'])
    op.drop_column('finances', 'u_cat_id')
    # ### end Alembic commands ###


def upgrade():
    op.alter_column('finances', 'u_cat_id', new_column_name='category_id')

