"""add timezone=True

Revision ID: e9ba9a2a2a13
Revises: ecabfd4c6045
Create Date: 2025-01-25 00:39:40.394130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ba9a2a2a13'
down_revision: Union[str, None] = 'ecabfd4c6045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
