"""update model User

Revision ID: ecabfd4c6045
Revises: 13b0f04fb4ff
Create Date: 2025-01-18 12:58:56.091563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecabfd4c6045'
down_revision: Union[str, None] = '13b0f04fb4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_categories_name_cat_key', 'user_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_categories_name_cat_key', 'user_categories', ['name_cat'])
    # ### end Alembic commands ###
